#include <iostream>
#include <mpfr.h>
#include "bvh-analysis/utils/parse.hpp"
#include "bvh-analysis/utils/build_bvh.hpp"
#include "bvh/single_ray_traverser.hpp"
#include "bvh/primitive_intersectors.hpp"

using Ray = bvh::Ray<float>;
using PrimitiveIntersector = bvh::ClosestPrimitiveIntersector<Bvh, Triangle>;
using Traverser = bvh::SingleRayTraverser<Bvh>;
using MPTraverser_5_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 5, 5>>;
using MPTraverser_5_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 5, 6>>;
using MPTraverser_5_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 5, 7>>;
using MPTraverser_5_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 5, 8>>;
using MPTraverser_6_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 6, 5>>;
using MPTraverser_6_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 6, 6>>;
using MPTraverser_6_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 6, 7>>;
using MPTraverser_6_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 6, 8>>;
using MPTraverser_7_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 7, 5>>;
using MPTraverser_7_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 7, 6>>;
using MPTraverser_7_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 7, 7>>;
using MPTraverser_7_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 7, 8>>;
using MPTraverser_8_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 8, 5>>;
using MPTraverser_8_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 8, 6>>;
using MPTraverser_8_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 8, 7>>;
using MPTraverser_8_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 8, 8>>;
using MPTraverser_9_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 9, 5>>;
using MPTraverser_9_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 9, 6>>;
using MPTraverser_9_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 9, 7>>;
using MPTraverser_9_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 9, 8>>;
using MPTraverser_10_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 10, 5>>;
using MPTraverser_10_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 10, 6>>;
using MPTraverser_10_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 10, 7>>;
using MPTraverser_10_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 10, 8>>;
using MPTraverser_11_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 11, 5>>;
using MPTraverser_11_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 11, 6>>;
using MPTraverser_11_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 11, 7>>;
using MPTraverser_11_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 11, 8>>;
using MPTraverser_12_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 12, 5>>;
using MPTraverser_12_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 12, 6>>;
using MPTraverser_12_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 12, 7>>;
using MPTraverser_12_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 12, 8>>;
using MPTraverser_13_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 13, 5>>;
using MPTraverser_13_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 13, 6>>;
using MPTraverser_13_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 13, 7>>;
using MPTraverser_13_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 13, 8>>;
using MPTraverser_14_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 14, 5>>;
using MPTraverser_14_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 14, 6>>;
using MPTraverser_14_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 14, 7>>;
using MPTraverser_14_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 14, 8>>;
using MPTraverser_15_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 15, 5>>;
using MPTraverser_15_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 15, 6>>;
using MPTraverser_15_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 15, 7>>;
using MPTraverser_15_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 15, 8>>;
using MPTraverser_16_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 16, 5>>;
using MPTraverser_16_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 16, 6>>;
using MPTraverser_16_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 16, 7>>;
using MPTraverser_16_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 16, 8>>;
using MPTraverser_17_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 17, 5>>;
using MPTraverser_17_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 17, 6>>;
using MPTraverser_17_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 17, 7>>;
using MPTraverser_17_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 17, 8>>;
using MPTraverser_18_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 18, 5>>;
using MPTraverser_18_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 18, 6>>;
using MPTraverser_18_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 18, 7>>;
using MPTraverser_18_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 18, 8>>;
using MPTraverser_19_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 19, 5>>;
using MPTraverser_19_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 19, 6>>;
using MPTraverser_19_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 19, 7>>;
using MPTraverser_19_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 19, 8>>;
using MPTraverser_20_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 20, 5>>;
using MPTraverser_20_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 20, 6>>;
using MPTraverser_20_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 20, 7>>;
using MPTraverser_20_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 20, 8>>;
using MPTraverser_21_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 21, 5>>;
using MPTraverser_21_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 21, 6>>;
using MPTraverser_21_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 21, 7>>;
using MPTraverser_21_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 21, 8>>;
using MPTraverser_22_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 22, 5>>;
using MPTraverser_22_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 22, 6>>;
using MPTraverser_22_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 22, 7>>;
using MPTraverser_22_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 22, 8>>;
using MPTraverser_23_5 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 23, 5>>;
using MPTraverser_23_6 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 23, 6>>;
using MPTraverser_23_7 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 23, 7>>;
using MPTraverser_23_8 = bvh::SingleRayTraverser<Bvh, 64, bvh::MPNodeIntersector<Bvh, 23, 8>>;

int main() {
    std::vector<Triangle> triangles = parse_ply("sponza.ply");

    auto [bboxes, centers] = bvh::compute_bounding_boxes_and_centers(triangles.data(), triangles.size());
    auto global_bbox = bvh::compute_bounding_boxes_union(bboxes.get(), triangles.size());
    Vector3 global_center = (global_bbox.max + global_bbox.min) * 0.5f;
    Vector3 global_dim = global_bbox.max - global_bbox.min;
    float global_scale = 2.f / std::max(global_dim[0], std::max(global_dim[1], global_dim[2]));

    for (auto &t : triangles) {
        t.p0 = (t.p0 - global_center) * global_scale;
        t.e1 = t.e1 * global_scale;
        t.e2 = t.e2 * global_scale;
        t.n = t.n * global_scale * global_scale;
    }

    Bvh bvh = build_bvh(triangles);
    std::cout << "BVH has " << bvh.node_count << " nodes" << std::endl;

    PrimitiveIntersector primitive_intersector(bvh, triangles.data());
    Traverser traverser(bvh);
    MPTraverser_5_5 mp_traverser_5_5(bvh);
    MPTraverser_5_6 mp_traverser_5_6(bvh);
    MPTraverser_5_7 mp_traverser_5_7(bvh);
    MPTraverser_5_8 mp_traverser_5_8(bvh);
    MPTraverser_6_5 mp_traverser_6_5(bvh);
    MPTraverser_6_6 mp_traverser_6_6(bvh);
    MPTraverser_6_7 mp_traverser_6_7(bvh);
    MPTraverser_6_8 mp_traverser_6_8(bvh);
    MPTraverser_7_5 mp_traverser_7_5(bvh);
    MPTraverser_7_6 mp_traverser_7_6(bvh);
    MPTraverser_7_7 mp_traverser_7_7(bvh);
    MPTraverser_7_8 mp_traverser_7_8(bvh);
    MPTraverser_8_5 mp_traverser_8_5(bvh);
    MPTraverser_8_6 mp_traverser_8_6(bvh);
    MPTraverser_8_7 mp_traverser_8_7(bvh);
    MPTraverser_8_8 mp_traverser_8_8(bvh);
    MPTraverser_9_5 mp_traverser_9_5(bvh);
    MPTraverser_9_6 mp_traverser_9_6(bvh);
    MPTraverser_9_7 mp_traverser_9_7(bvh);
    MPTraverser_9_8 mp_traverser_9_8(bvh);
    MPTraverser_10_5 mp_traverser_10_5(bvh);
    MPTraverser_10_6 mp_traverser_10_6(bvh);
    MPTraverser_10_7 mp_traverser_10_7(bvh);
    MPTraverser_10_8 mp_traverser_10_8(bvh);
    MPTraverser_11_5 mp_traverser_11_5(bvh);
    MPTraverser_11_6 mp_traverser_11_6(bvh);
    MPTraverser_11_7 mp_traverser_11_7(bvh);
    MPTraverser_11_8 mp_traverser_11_8(bvh);
    MPTraverser_12_5 mp_traverser_12_5(bvh);
    MPTraverser_12_6 mp_traverser_12_6(bvh);
    MPTraverser_12_7 mp_traverser_12_7(bvh);
    MPTraverser_12_8 mp_traverser_12_8(bvh);
    MPTraverser_13_5 mp_traverser_13_5(bvh);
    MPTraverser_13_6 mp_traverser_13_6(bvh);
    MPTraverser_13_7 mp_traverser_13_7(bvh);
    MPTraverser_13_8 mp_traverser_13_8(bvh);
    MPTraverser_14_5 mp_traverser_14_5(bvh);
    MPTraverser_14_6 mp_traverser_14_6(bvh);
    MPTraverser_14_7 mp_traverser_14_7(bvh);
    MPTraverser_14_8 mp_traverser_14_8(bvh);
    MPTraverser_15_5 mp_traverser_15_5(bvh);
    MPTraverser_15_6 mp_traverser_15_6(bvh);
    MPTraverser_15_7 mp_traverser_15_7(bvh);
    MPTraverser_15_8 mp_traverser_15_8(bvh);
    MPTraverser_16_5 mp_traverser_16_5(bvh);
    MPTraverser_16_6 mp_traverser_16_6(bvh);
    MPTraverser_16_7 mp_traverser_16_7(bvh);
    MPTraverser_16_8 mp_traverser_16_8(bvh);
    MPTraverser_17_5 mp_traverser_17_5(bvh);
    MPTraverser_17_6 mp_traverser_17_6(bvh);
    MPTraverser_17_7 mp_traverser_17_7(bvh);
    MPTraverser_17_8 mp_traverser_17_8(bvh);
    MPTraverser_18_5 mp_traverser_18_5(bvh);
    MPTraverser_18_6 mp_traverser_18_6(bvh);
    MPTraverser_18_7 mp_traverser_18_7(bvh);
    MPTraverser_18_8 mp_traverser_18_8(bvh);
    MPTraverser_19_5 mp_traverser_19_5(bvh);
    MPTraverser_19_6 mp_traverser_19_6(bvh);
    MPTraverser_19_7 mp_traverser_19_7(bvh);
    MPTraverser_19_8 mp_traverser_19_8(bvh);
    MPTraverser_20_5 mp_traverser_20_5(bvh);
    MPTraverser_20_6 mp_traverser_20_6(bvh);
    MPTraverser_20_7 mp_traverser_20_7(bvh);
    MPTraverser_20_8 mp_traverser_20_8(bvh);
    MPTraverser_21_5 mp_traverser_21_5(bvh);
    MPTraverser_21_6 mp_traverser_21_6(bvh);
    MPTraverser_21_7 mp_traverser_21_7(bvh);
    MPTraverser_21_8 mp_traverser_21_8(bvh);
    MPTraverser_22_5 mp_traverser_22_5(bvh);
    MPTraverser_22_6 mp_traverser_22_6(bvh);
    MPTraverser_22_7 mp_traverser_22_7(bvh);
    MPTraverser_22_8 mp_traverser_22_8(bvh);
    MPTraverser_23_5 mp_traverser_23_5(bvh);
    MPTraverser_23_6 mp_traverser_23_6(bvh);
    MPTraverser_23_7 mp_traverser_23_7(bvh);
    MPTraverser_23_8 mp_traverser_23_8(bvh);

    std::ofstream traversal_steps_5_5_file("traversal_steps_5_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_5_5_file("intersections_5_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_5_6_file("traversal_steps_5_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_5_6_file("intersections_5_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_5_7_file("traversal_steps_5_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_5_7_file("intersections_5_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_5_8_file("traversal_steps_5_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_5_8_file("intersections_5_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_6_5_file("traversal_steps_6_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_6_5_file("intersections_6_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_6_6_file("traversal_steps_6_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_6_6_file("intersections_6_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_6_7_file("traversal_steps_6_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_6_7_file("intersections_6_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_6_8_file("traversal_steps_6_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_6_8_file("intersections_6_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_7_5_file("traversal_steps_7_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_7_5_file("intersections_7_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_7_6_file("traversal_steps_7_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_7_6_file("intersections_7_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_7_7_file("traversal_steps_7_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_7_7_file("intersections_7_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_7_8_file("traversal_steps_7_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_7_8_file("intersections_7_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_8_5_file("traversal_steps_8_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_8_5_file("intersections_8_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_8_6_file("traversal_steps_8_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_8_6_file("intersections_8_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_8_7_file("traversal_steps_8_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_8_7_file("intersections_8_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_8_8_file("traversal_steps_8_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_8_8_file("intersections_8_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_9_5_file("traversal_steps_9_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_9_5_file("intersections_9_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_9_6_file("traversal_steps_9_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_9_6_file("intersections_9_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_9_7_file("traversal_steps_9_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_9_7_file("intersections_9_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_9_8_file("traversal_steps_9_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_9_8_file("intersections_9_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_10_5_file("traversal_steps_10_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_10_5_file("intersections_10_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_10_6_file("traversal_steps_10_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_10_6_file("intersections_10_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_10_7_file("traversal_steps_10_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_10_7_file("intersections_10_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_10_8_file("traversal_steps_10_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_10_8_file("intersections_10_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_11_5_file("traversal_steps_11_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_11_5_file("intersections_11_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_11_6_file("traversal_steps_11_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_11_6_file("intersections_11_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_11_7_file("traversal_steps_11_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_11_7_file("intersections_11_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_11_8_file("traversal_steps_11_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_11_8_file("intersections_11_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_12_5_file("traversal_steps_12_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_12_5_file("intersections_12_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_12_6_file("traversal_steps_12_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_12_6_file("intersections_12_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_12_7_file("traversal_steps_12_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_12_7_file("intersections_12_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_12_8_file("traversal_steps_12_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_12_8_file("intersections_12_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_13_5_file("traversal_steps_13_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_13_5_file("intersections_13_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_13_6_file("traversal_steps_13_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_13_6_file("intersections_13_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_13_7_file("traversal_steps_13_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_13_7_file("intersections_13_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_13_8_file("traversal_steps_13_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_13_8_file("intersections_13_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_14_5_file("traversal_steps_14_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_14_5_file("intersections_14_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_14_6_file("traversal_steps_14_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_14_6_file("intersections_14_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_14_7_file("traversal_steps_14_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_14_7_file("intersections_14_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_14_8_file("traversal_steps_14_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_14_8_file("intersections_14_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_15_5_file("traversal_steps_15_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_15_5_file("intersections_15_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_15_6_file("traversal_steps_15_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_15_6_file("intersections_15_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_15_7_file("traversal_steps_15_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_15_7_file("intersections_15_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_15_8_file("traversal_steps_15_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_15_8_file("intersections_15_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_16_5_file("traversal_steps_16_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_16_5_file("intersections_16_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_16_6_file("traversal_steps_16_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_16_6_file("intersections_16_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_16_7_file("traversal_steps_16_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_16_7_file("intersections_16_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_16_8_file("traversal_steps_16_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_16_8_file("intersections_16_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_17_5_file("traversal_steps_17_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_17_5_file("intersections_17_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_17_6_file("traversal_steps_17_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_17_6_file("intersections_17_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_17_7_file("traversal_steps_17_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_17_7_file("intersections_17_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_17_8_file("traversal_steps_17_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_17_8_file("intersections_17_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_18_5_file("traversal_steps_18_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_18_5_file("intersections_18_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_18_6_file("traversal_steps_18_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_18_6_file("intersections_18_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_18_7_file("traversal_steps_18_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_18_7_file("intersections_18_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_18_8_file("traversal_steps_18_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_18_8_file("intersections_18_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_19_5_file("traversal_steps_19_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_19_5_file("intersections_19_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_19_6_file("traversal_steps_19_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_19_6_file("intersections_19_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_19_7_file("traversal_steps_19_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_19_7_file("intersections_19_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_19_8_file("traversal_steps_19_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_19_8_file("intersections_19_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_20_5_file("traversal_steps_20_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_20_5_file("intersections_20_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_20_6_file("traversal_steps_20_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_20_6_file("intersections_20_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_20_7_file("traversal_steps_20_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_20_7_file("intersections_20_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_20_8_file("traversal_steps_20_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_20_8_file("intersections_20_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_21_5_file("traversal_steps_21_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_21_5_file("intersections_21_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_21_6_file("traversal_steps_21_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_21_6_file("intersections_21_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_21_7_file("traversal_steps_21_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_21_7_file("intersections_21_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_21_8_file("traversal_steps_21_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_21_8_file("intersections_21_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_22_5_file("traversal_steps_22_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_22_5_file("intersections_22_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_22_6_file("traversal_steps_22_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_22_6_file("intersections_22_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_22_7_file("traversal_steps_22_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_22_7_file("intersections_22_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_22_8_file("traversal_steps_22_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_22_8_file("intersections_22_8.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_23_5_file("traversal_steps_23_5.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_23_5_file("intersections_23_5.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_23_6_file("traversal_steps_23_6.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_23_6_file("intersections_23_6.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_23_7_file("traversal_steps_23_7.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_23_7_file("intersections_23_7.bin", std::ios::out | std::ios::binary);
    std::ofstream traversal_steps_23_8_file("traversal_steps_23_8.bin", std::ios::out | std::ios::binary);
    std::ofstream intersections_23_8_file("intersections_23_8.bin", std::ios::out | std::ios::binary);

    std::ofstream ref_traversal_steps_file("ref_traversal_steps.bin", std::ios::out | std::ios::binary);
    std::ofstream ref_intersections_file("ref_intersections.bin", std::ios::out | std::ios::binary);
    std::ifstream ray_queries_file("ray_queries.bin", std::ios::in | std::ios::binary);
    float r[7];
    int finished_cnt = 0;
    while (ray_queries_file.read(reinterpret_cast<char*>(&r), 7 * sizeof(float))) {
        if (rand() % 1000 != 0) continue;

        Vector3 origin(r[0], r[1], r[2]);
        Vector3 direction(r[3], r[4], r[5]);
        float tmax = r[6];

        origin = (origin - global_center) * global_scale;
        tmax = tmax * global_scale;

        Ray ray(
                origin,
                direction,
                0.f,
                tmax
        );

        MPTraverser_5_5::Statistics statistics_5_5;
        auto result_5_5 = mp_traverser_5_5.traverse(ray, primitive_intersector, statistics_5_5);
        MPTraverser_5_6::Statistics statistics_5_6;
        auto result_5_6 = mp_traverser_5_6.traverse(ray, primitive_intersector, statistics_5_6);
        MPTraverser_5_7::Statistics statistics_5_7;
        auto result_5_7 = mp_traverser_5_7.traverse(ray, primitive_intersector, statistics_5_7);
        MPTraverser_5_8::Statistics statistics_5_8;
        auto result_5_8 = mp_traverser_5_8.traverse(ray, primitive_intersector, statistics_5_8);
        MPTraverser_6_5::Statistics statistics_6_5;
        auto result_6_5 = mp_traverser_6_5.traverse(ray, primitive_intersector, statistics_6_5);
        MPTraverser_6_6::Statistics statistics_6_6;
        auto result_6_6 = mp_traverser_6_6.traverse(ray, primitive_intersector, statistics_6_6);
        MPTraverser_6_7::Statistics statistics_6_7;
        auto result_6_7 = mp_traverser_6_7.traverse(ray, primitive_intersector, statistics_6_7);
        MPTraverser_6_8::Statistics statistics_6_8;
        auto result_6_8 = mp_traverser_6_8.traverse(ray, primitive_intersector, statistics_6_8);
        MPTraverser_7_5::Statistics statistics_7_5;
        auto result_7_5 = mp_traverser_7_5.traverse(ray, primitive_intersector, statistics_7_5);
        MPTraverser_7_6::Statistics statistics_7_6;
        auto result_7_6 = mp_traverser_7_6.traverse(ray, primitive_intersector, statistics_7_6);
        MPTraverser_7_7::Statistics statistics_7_7;
        auto result_7_7 = mp_traverser_7_7.traverse(ray, primitive_intersector, statistics_7_7);
        MPTraverser_7_8::Statistics statistics_7_8;
        auto result_7_8 = mp_traverser_7_8.traverse(ray, primitive_intersector, statistics_7_8);
        MPTraverser_8_5::Statistics statistics_8_5;
        auto result_8_5 = mp_traverser_8_5.traverse(ray, primitive_intersector, statistics_8_5);
        MPTraverser_8_6::Statistics statistics_8_6;
        auto result_8_6 = mp_traverser_8_6.traverse(ray, primitive_intersector, statistics_8_6);
        MPTraverser_8_7::Statistics statistics_8_7;
        auto result_8_7 = mp_traverser_8_7.traverse(ray, primitive_intersector, statistics_8_7);
        MPTraverser_8_8::Statistics statistics_8_8;
        auto result_8_8 = mp_traverser_8_8.traverse(ray, primitive_intersector, statistics_8_8);
        MPTraverser_9_5::Statistics statistics_9_5;
        auto result_9_5 = mp_traverser_9_5.traverse(ray, primitive_intersector, statistics_9_5);
        MPTraverser_9_6::Statistics statistics_9_6;
        auto result_9_6 = mp_traverser_9_6.traverse(ray, primitive_intersector, statistics_9_6);
        MPTraverser_9_7::Statistics statistics_9_7;
        auto result_9_7 = mp_traverser_9_7.traverse(ray, primitive_intersector, statistics_9_7);
        MPTraverser_9_8::Statistics statistics_9_8;
        auto result_9_8 = mp_traverser_9_8.traverse(ray, primitive_intersector, statistics_9_8);
        MPTraverser_10_5::Statistics statistics_10_5;
        auto result_10_5 = mp_traverser_10_5.traverse(ray, primitive_intersector, statistics_10_5);
        MPTraverser_10_6::Statistics statistics_10_6;
        auto result_10_6 = mp_traverser_10_6.traverse(ray, primitive_intersector, statistics_10_6);
        MPTraverser_10_7::Statistics statistics_10_7;
        auto result_10_7 = mp_traverser_10_7.traverse(ray, primitive_intersector, statistics_10_7);
        MPTraverser_10_8::Statistics statistics_10_8;
        auto result_10_8 = mp_traverser_10_8.traverse(ray, primitive_intersector, statistics_10_8);
        MPTraverser_11_5::Statistics statistics_11_5;
        auto result_11_5 = mp_traverser_11_5.traverse(ray, primitive_intersector, statistics_11_5);
        MPTraverser_11_6::Statistics statistics_11_6;
        auto result_11_6 = mp_traverser_11_6.traverse(ray, primitive_intersector, statistics_11_6);
        MPTraverser_11_7::Statistics statistics_11_7;
        auto result_11_7 = mp_traverser_11_7.traverse(ray, primitive_intersector, statistics_11_7);
        MPTraverser_11_8::Statistics statistics_11_8;
        auto result_11_8 = mp_traverser_11_8.traverse(ray, primitive_intersector, statistics_11_8);
        MPTraverser_12_5::Statistics statistics_12_5;
        auto result_12_5 = mp_traverser_12_5.traverse(ray, primitive_intersector, statistics_12_5);
        MPTraverser_12_6::Statistics statistics_12_6;
        auto result_12_6 = mp_traverser_12_6.traverse(ray, primitive_intersector, statistics_12_6);
        MPTraverser_12_7::Statistics statistics_12_7;
        auto result_12_7 = mp_traverser_12_7.traverse(ray, primitive_intersector, statistics_12_7);
        MPTraverser_12_8::Statistics statistics_12_8;
        auto result_12_8 = mp_traverser_12_8.traverse(ray, primitive_intersector, statistics_12_8);
        MPTraverser_13_5::Statistics statistics_13_5;
        auto result_13_5 = mp_traverser_13_5.traverse(ray, primitive_intersector, statistics_13_5);
        MPTraverser_13_6::Statistics statistics_13_6;
        auto result_13_6 = mp_traverser_13_6.traverse(ray, primitive_intersector, statistics_13_6);
        MPTraverser_13_7::Statistics statistics_13_7;
        auto result_13_7 = mp_traverser_13_7.traverse(ray, primitive_intersector, statistics_13_7);
        MPTraverser_13_8::Statistics statistics_13_8;
        auto result_13_8 = mp_traverser_13_8.traverse(ray, primitive_intersector, statistics_13_8);
        MPTraverser_14_5::Statistics statistics_14_5;
        auto result_14_5 = mp_traverser_14_5.traverse(ray, primitive_intersector, statistics_14_5);
        MPTraverser_14_6::Statistics statistics_14_6;
        auto result_14_6 = mp_traverser_14_6.traverse(ray, primitive_intersector, statistics_14_6);
        MPTraverser_14_7::Statistics statistics_14_7;
        auto result_14_7 = mp_traverser_14_7.traverse(ray, primitive_intersector, statistics_14_7);
        MPTraverser_14_8::Statistics statistics_14_8;
        auto result_14_8 = mp_traverser_14_8.traverse(ray, primitive_intersector, statistics_14_8);
        MPTraverser_15_5::Statistics statistics_15_5;
        auto result_15_5 = mp_traverser_15_5.traverse(ray, primitive_intersector, statistics_15_5);
        MPTraverser_15_6::Statistics statistics_15_6;
        auto result_15_6 = mp_traverser_15_6.traverse(ray, primitive_intersector, statistics_15_6);
        MPTraverser_15_7::Statistics statistics_15_7;
        auto result_15_7 = mp_traverser_15_7.traverse(ray, primitive_intersector, statistics_15_7);
        MPTraverser_15_8::Statistics statistics_15_8;
        auto result_15_8 = mp_traverser_15_8.traverse(ray, primitive_intersector, statistics_15_8);
        MPTraverser_16_5::Statistics statistics_16_5;
        auto result_16_5 = mp_traverser_16_5.traverse(ray, primitive_intersector, statistics_16_5);
        MPTraverser_16_6::Statistics statistics_16_6;
        auto result_16_6 = mp_traverser_16_6.traverse(ray, primitive_intersector, statistics_16_6);
        MPTraverser_16_7::Statistics statistics_16_7;
        auto result_16_7 = mp_traverser_16_7.traverse(ray, primitive_intersector, statistics_16_7);
        MPTraverser_16_8::Statistics statistics_16_8;
        auto result_16_8 = mp_traverser_16_8.traverse(ray, primitive_intersector, statistics_16_8);
        MPTraverser_17_5::Statistics statistics_17_5;
        auto result_17_5 = mp_traverser_17_5.traverse(ray, primitive_intersector, statistics_17_5);
        MPTraverser_17_6::Statistics statistics_17_6;
        auto result_17_6 = mp_traverser_17_6.traverse(ray, primitive_intersector, statistics_17_6);
        MPTraverser_17_7::Statistics statistics_17_7;
        auto result_17_7 = mp_traverser_17_7.traverse(ray, primitive_intersector, statistics_17_7);
        MPTraverser_17_8::Statistics statistics_17_8;
        auto result_17_8 = mp_traverser_17_8.traverse(ray, primitive_intersector, statistics_17_8);
        MPTraverser_18_5::Statistics statistics_18_5;
        auto result_18_5 = mp_traverser_18_5.traverse(ray, primitive_intersector, statistics_18_5);
        MPTraverser_18_6::Statistics statistics_18_6;
        auto result_18_6 = mp_traverser_18_6.traverse(ray, primitive_intersector, statistics_18_6);
        MPTraverser_18_7::Statistics statistics_18_7;
        auto result_18_7 = mp_traverser_18_7.traverse(ray, primitive_intersector, statistics_18_7);
        MPTraverser_18_8::Statistics statistics_18_8;
        auto result_18_8 = mp_traverser_18_8.traverse(ray, primitive_intersector, statistics_18_8);
        MPTraverser_19_5::Statistics statistics_19_5;
        auto result_19_5 = mp_traverser_19_5.traverse(ray, primitive_intersector, statistics_19_5);
        MPTraverser_19_6::Statistics statistics_19_6;
        auto result_19_6 = mp_traverser_19_6.traverse(ray, primitive_intersector, statistics_19_6);
        MPTraverser_19_7::Statistics statistics_19_7;
        auto result_19_7 = mp_traverser_19_7.traverse(ray, primitive_intersector, statistics_19_7);
        MPTraverser_19_8::Statistics statistics_19_8;
        auto result_19_8 = mp_traverser_19_8.traverse(ray, primitive_intersector, statistics_19_8);
        MPTraverser_20_5::Statistics statistics_20_5;
        auto result_20_5 = mp_traverser_20_5.traverse(ray, primitive_intersector, statistics_20_5);
        MPTraverser_20_6::Statistics statistics_20_6;
        auto result_20_6 = mp_traverser_20_6.traverse(ray, primitive_intersector, statistics_20_6);
        MPTraverser_20_7::Statistics statistics_20_7;
        auto result_20_7 = mp_traverser_20_7.traverse(ray, primitive_intersector, statistics_20_7);
        MPTraverser_20_8::Statistics statistics_20_8;
        auto result_20_8 = mp_traverser_20_8.traverse(ray, primitive_intersector, statistics_20_8);
        MPTraverser_21_5::Statistics statistics_21_5;
        auto result_21_5 = mp_traverser_21_5.traverse(ray, primitive_intersector, statistics_21_5);
        MPTraverser_21_6::Statistics statistics_21_6;
        auto result_21_6 = mp_traverser_21_6.traverse(ray, primitive_intersector, statistics_21_6);
        MPTraverser_21_7::Statistics statistics_21_7;
        auto result_21_7 = mp_traverser_21_7.traverse(ray, primitive_intersector, statistics_21_7);
        MPTraverser_21_8::Statistics statistics_21_8;
        auto result_21_8 = mp_traverser_21_8.traverse(ray, primitive_intersector, statistics_21_8);
        MPTraverser_22_5::Statistics statistics_22_5;
        auto result_22_5 = mp_traverser_22_5.traverse(ray, primitive_intersector, statistics_22_5);
        MPTraverser_22_6::Statistics statistics_22_6;
        auto result_22_6 = mp_traverser_22_6.traverse(ray, primitive_intersector, statistics_22_6);
        MPTraverser_22_7::Statistics statistics_22_7;
        auto result_22_7 = mp_traverser_22_7.traverse(ray, primitive_intersector, statistics_22_7);
        MPTraverser_22_8::Statistics statistics_22_8;
        auto result_22_8 = mp_traverser_22_8.traverse(ray, primitive_intersector, statistics_22_8);
        MPTraverser_23_5::Statistics statistics_23_5;
        auto result_23_5 = mp_traverser_23_5.traverse(ray, primitive_intersector, statistics_23_5);
        MPTraverser_23_6::Statistics statistics_23_6;
        auto result_23_6 = mp_traverser_23_6.traverse(ray, primitive_intersector, statistics_23_6);
        MPTraverser_23_7::Statistics statistics_23_7;
        auto result_23_7 = mp_traverser_23_7.traverse(ray, primitive_intersector, statistics_23_7);
        MPTraverser_23_8::Statistics statistics_23_8;
        auto result_23_8 = mp_traverser_23_8.traverse(ray, primitive_intersector, statistics_23_8);

        Traverser::Statistics ref_statistics;
        auto ref_result = traverser.traverse(ray, primitive_intersector, ref_statistics);

        traversal_steps_5_5_file.write(reinterpret_cast<const char*>(&statistics_5_5.traversal_steps), sizeof(size_t));
        intersections_5_5_file.write(reinterpret_cast<const char*>(&statistics_5_5.intersections), sizeof(size_t));
        traversal_steps_5_6_file.write(reinterpret_cast<const char*>(&statistics_5_6.traversal_steps), sizeof(size_t));
        intersections_5_6_file.write(reinterpret_cast<const char*>(&statistics_5_6.intersections), sizeof(size_t));
        traversal_steps_5_7_file.write(reinterpret_cast<const char*>(&statistics_5_7.traversal_steps), sizeof(size_t));
        intersections_5_7_file.write(reinterpret_cast<const char*>(&statistics_5_7.intersections), sizeof(size_t));
        traversal_steps_5_8_file.write(reinterpret_cast<const char*>(&statistics_5_8.traversal_steps), sizeof(size_t));
        intersections_5_8_file.write(reinterpret_cast<const char*>(&statistics_5_8.intersections), sizeof(size_t));
        traversal_steps_6_5_file.write(reinterpret_cast<const char*>(&statistics_6_5.traversal_steps), sizeof(size_t));
        intersections_6_5_file.write(reinterpret_cast<const char*>(&statistics_6_5.intersections), sizeof(size_t));
        traversal_steps_6_6_file.write(reinterpret_cast<const char*>(&statistics_6_6.traversal_steps), sizeof(size_t));
        intersections_6_6_file.write(reinterpret_cast<const char*>(&statistics_6_6.intersections), sizeof(size_t));
        traversal_steps_6_7_file.write(reinterpret_cast<const char*>(&statistics_6_7.traversal_steps), sizeof(size_t));
        intersections_6_7_file.write(reinterpret_cast<const char*>(&statistics_6_7.intersections), sizeof(size_t));
        traversal_steps_6_8_file.write(reinterpret_cast<const char*>(&statistics_6_8.traversal_steps), sizeof(size_t));
        intersections_6_8_file.write(reinterpret_cast<const char*>(&statistics_6_8.intersections), sizeof(size_t));
        traversal_steps_7_5_file.write(reinterpret_cast<const char*>(&statistics_7_5.traversal_steps), sizeof(size_t));
        intersections_7_5_file.write(reinterpret_cast<const char*>(&statistics_7_5.intersections), sizeof(size_t));
        traversal_steps_7_6_file.write(reinterpret_cast<const char*>(&statistics_7_6.traversal_steps), sizeof(size_t));
        intersections_7_6_file.write(reinterpret_cast<const char*>(&statistics_7_6.intersections), sizeof(size_t));
        traversal_steps_7_7_file.write(reinterpret_cast<const char*>(&statistics_7_7.traversal_steps), sizeof(size_t));
        intersections_7_7_file.write(reinterpret_cast<const char*>(&statistics_7_7.intersections), sizeof(size_t));
        traversal_steps_7_8_file.write(reinterpret_cast<const char*>(&statistics_7_8.traversal_steps), sizeof(size_t));
        intersections_7_8_file.write(reinterpret_cast<const char*>(&statistics_7_8.intersections), sizeof(size_t));
        traversal_steps_8_5_file.write(reinterpret_cast<const char*>(&statistics_8_5.traversal_steps), sizeof(size_t));
        intersections_8_5_file.write(reinterpret_cast<const char*>(&statistics_8_5.intersections), sizeof(size_t));
        traversal_steps_8_6_file.write(reinterpret_cast<const char*>(&statistics_8_6.traversal_steps), sizeof(size_t));
        intersections_8_6_file.write(reinterpret_cast<const char*>(&statistics_8_6.intersections), sizeof(size_t));
        traversal_steps_8_7_file.write(reinterpret_cast<const char*>(&statistics_8_7.traversal_steps), sizeof(size_t));
        intersections_8_7_file.write(reinterpret_cast<const char*>(&statistics_8_7.intersections), sizeof(size_t));
        traversal_steps_8_8_file.write(reinterpret_cast<const char*>(&statistics_8_8.traversal_steps), sizeof(size_t));
        intersections_8_8_file.write(reinterpret_cast<const char*>(&statistics_8_8.intersections), sizeof(size_t));
        traversal_steps_9_5_file.write(reinterpret_cast<const char*>(&statistics_9_5.traversal_steps), sizeof(size_t));
        intersections_9_5_file.write(reinterpret_cast<const char*>(&statistics_9_5.intersections), sizeof(size_t));
        traversal_steps_9_6_file.write(reinterpret_cast<const char*>(&statistics_9_6.traversal_steps), sizeof(size_t));
        intersections_9_6_file.write(reinterpret_cast<const char*>(&statistics_9_6.intersections), sizeof(size_t));
        traversal_steps_9_7_file.write(reinterpret_cast<const char*>(&statistics_9_7.traversal_steps), sizeof(size_t));
        intersections_9_7_file.write(reinterpret_cast<const char*>(&statistics_9_7.intersections), sizeof(size_t));
        traversal_steps_9_8_file.write(reinterpret_cast<const char*>(&statistics_9_8.traversal_steps), sizeof(size_t));
        intersections_9_8_file.write(reinterpret_cast<const char*>(&statistics_9_8.intersections), sizeof(size_t));
        traversal_steps_10_5_file.write(reinterpret_cast<const char*>(&statistics_10_5.traversal_steps), sizeof(size_t));
        intersections_10_5_file.write(reinterpret_cast<const char*>(&statistics_10_5.intersections), sizeof(size_t));
        traversal_steps_10_6_file.write(reinterpret_cast<const char*>(&statistics_10_6.traversal_steps), sizeof(size_t));
        intersections_10_6_file.write(reinterpret_cast<const char*>(&statistics_10_6.intersections), sizeof(size_t));
        traversal_steps_10_7_file.write(reinterpret_cast<const char*>(&statistics_10_7.traversal_steps), sizeof(size_t));
        intersections_10_7_file.write(reinterpret_cast<const char*>(&statistics_10_7.intersections), sizeof(size_t));
        traversal_steps_10_8_file.write(reinterpret_cast<const char*>(&statistics_10_8.traversal_steps), sizeof(size_t));
        intersections_10_8_file.write(reinterpret_cast<const char*>(&statistics_10_8.intersections), sizeof(size_t));
        traversal_steps_11_5_file.write(reinterpret_cast<const char*>(&statistics_11_5.traversal_steps), sizeof(size_t));
        intersections_11_5_file.write(reinterpret_cast<const char*>(&statistics_11_5.intersections), sizeof(size_t));
        traversal_steps_11_6_file.write(reinterpret_cast<const char*>(&statistics_11_6.traversal_steps), sizeof(size_t));
        intersections_11_6_file.write(reinterpret_cast<const char*>(&statistics_11_6.intersections), sizeof(size_t));
        traversal_steps_11_7_file.write(reinterpret_cast<const char*>(&statistics_11_7.traversal_steps), sizeof(size_t));
        intersections_11_7_file.write(reinterpret_cast<const char*>(&statistics_11_7.intersections), sizeof(size_t));
        traversal_steps_11_8_file.write(reinterpret_cast<const char*>(&statistics_11_8.traversal_steps), sizeof(size_t));
        intersections_11_8_file.write(reinterpret_cast<const char*>(&statistics_11_8.intersections), sizeof(size_t));
        traversal_steps_12_5_file.write(reinterpret_cast<const char*>(&statistics_12_5.traversal_steps), sizeof(size_t));
        intersections_12_5_file.write(reinterpret_cast<const char*>(&statistics_12_5.intersections), sizeof(size_t));
        traversal_steps_12_6_file.write(reinterpret_cast<const char*>(&statistics_12_6.traversal_steps), sizeof(size_t));
        intersections_12_6_file.write(reinterpret_cast<const char*>(&statistics_12_6.intersections), sizeof(size_t));
        traversal_steps_12_7_file.write(reinterpret_cast<const char*>(&statistics_12_7.traversal_steps), sizeof(size_t));
        intersections_12_7_file.write(reinterpret_cast<const char*>(&statistics_12_7.intersections), sizeof(size_t));
        traversal_steps_12_8_file.write(reinterpret_cast<const char*>(&statistics_12_8.traversal_steps), sizeof(size_t));
        intersections_12_8_file.write(reinterpret_cast<const char*>(&statistics_12_8.intersections), sizeof(size_t));
        traversal_steps_13_5_file.write(reinterpret_cast<const char*>(&statistics_13_5.traversal_steps), sizeof(size_t));
        intersections_13_5_file.write(reinterpret_cast<const char*>(&statistics_13_5.intersections), sizeof(size_t));
        traversal_steps_13_6_file.write(reinterpret_cast<const char*>(&statistics_13_6.traversal_steps), sizeof(size_t));
        intersections_13_6_file.write(reinterpret_cast<const char*>(&statistics_13_6.intersections), sizeof(size_t));
        traversal_steps_13_7_file.write(reinterpret_cast<const char*>(&statistics_13_7.traversal_steps), sizeof(size_t));
        intersections_13_7_file.write(reinterpret_cast<const char*>(&statistics_13_7.intersections), sizeof(size_t));
        traversal_steps_13_8_file.write(reinterpret_cast<const char*>(&statistics_13_8.traversal_steps), sizeof(size_t));
        intersections_13_8_file.write(reinterpret_cast<const char*>(&statistics_13_8.intersections), sizeof(size_t));
        traversal_steps_14_5_file.write(reinterpret_cast<const char*>(&statistics_14_5.traversal_steps), sizeof(size_t));
        intersections_14_5_file.write(reinterpret_cast<const char*>(&statistics_14_5.intersections), sizeof(size_t));
        traversal_steps_14_6_file.write(reinterpret_cast<const char*>(&statistics_14_6.traversal_steps), sizeof(size_t));
        intersections_14_6_file.write(reinterpret_cast<const char*>(&statistics_14_6.intersections), sizeof(size_t));
        traversal_steps_14_7_file.write(reinterpret_cast<const char*>(&statistics_14_7.traversal_steps), sizeof(size_t));
        intersections_14_7_file.write(reinterpret_cast<const char*>(&statistics_14_7.intersections), sizeof(size_t));
        traversal_steps_14_8_file.write(reinterpret_cast<const char*>(&statistics_14_8.traversal_steps), sizeof(size_t));
        intersections_14_8_file.write(reinterpret_cast<const char*>(&statistics_14_8.intersections), sizeof(size_t));
        traversal_steps_15_5_file.write(reinterpret_cast<const char*>(&statistics_15_5.traversal_steps), sizeof(size_t));
        intersections_15_5_file.write(reinterpret_cast<const char*>(&statistics_15_5.intersections), sizeof(size_t));
        traversal_steps_15_6_file.write(reinterpret_cast<const char*>(&statistics_15_6.traversal_steps), sizeof(size_t));
        intersections_15_6_file.write(reinterpret_cast<const char*>(&statistics_15_6.intersections), sizeof(size_t));
        traversal_steps_15_7_file.write(reinterpret_cast<const char*>(&statistics_15_7.traversal_steps), sizeof(size_t));
        intersections_15_7_file.write(reinterpret_cast<const char*>(&statistics_15_7.intersections), sizeof(size_t));
        traversal_steps_15_8_file.write(reinterpret_cast<const char*>(&statistics_15_8.traversal_steps), sizeof(size_t));
        intersections_15_8_file.write(reinterpret_cast<const char*>(&statistics_15_8.intersections), sizeof(size_t));
        traversal_steps_16_5_file.write(reinterpret_cast<const char*>(&statistics_16_5.traversal_steps), sizeof(size_t));
        intersections_16_5_file.write(reinterpret_cast<const char*>(&statistics_16_5.intersections), sizeof(size_t));
        traversal_steps_16_6_file.write(reinterpret_cast<const char*>(&statistics_16_6.traversal_steps), sizeof(size_t));
        intersections_16_6_file.write(reinterpret_cast<const char*>(&statistics_16_6.intersections), sizeof(size_t));
        traversal_steps_16_7_file.write(reinterpret_cast<const char*>(&statistics_16_7.traversal_steps), sizeof(size_t));
        intersections_16_7_file.write(reinterpret_cast<const char*>(&statistics_16_7.intersections), sizeof(size_t));
        traversal_steps_16_8_file.write(reinterpret_cast<const char*>(&statistics_16_8.traversal_steps), sizeof(size_t));
        intersections_16_8_file.write(reinterpret_cast<const char*>(&statistics_16_8.intersections), sizeof(size_t));
        traversal_steps_17_5_file.write(reinterpret_cast<const char*>(&statistics_17_5.traversal_steps), sizeof(size_t));
        intersections_17_5_file.write(reinterpret_cast<const char*>(&statistics_17_5.intersections), sizeof(size_t));
        traversal_steps_17_6_file.write(reinterpret_cast<const char*>(&statistics_17_6.traversal_steps), sizeof(size_t));
        intersections_17_6_file.write(reinterpret_cast<const char*>(&statistics_17_6.intersections), sizeof(size_t));
        traversal_steps_17_7_file.write(reinterpret_cast<const char*>(&statistics_17_7.traversal_steps), sizeof(size_t));
        intersections_17_7_file.write(reinterpret_cast<const char*>(&statistics_17_7.intersections), sizeof(size_t));
        traversal_steps_17_8_file.write(reinterpret_cast<const char*>(&statistics_17_8.traversal_steps), sizeof(size_t));
        intersections_17_8_file.write(reinterpret_cast<const char*>(&statistics_17_8.intersections), sizeof(size_t));
        traversal_steps_18_5_file.write(reinterpret_cast<const char*>(&statistics_18_5.traversal_steps), sizeof(size_t));
        intersections_18_5_file.write(reinterpret_cast<const char*>(&statistics_18_5.intersections), sizeof(size_t));
        traversal_steps_18_6_file.write(reinterpret_cast<const char*>(&statistics_18_6.traversal_steps), sizeof(size_t));
        intersections_18_6_file.write(reinterpret_cast<const char*>(&statistics_18_6.intersections), sizeof(size_t));
        traversal_steps_18_7_file.write(reinterpret_cast<const char*>(&statistics_18_7.traversal_steps), sizeof(size_t));
        intersections_18_7_file.write(reinterpret_cast<const char*>(&statistics_18_7.intersections), sizeof(size_t));
        traversal_steps_18_8_file.write(reinterpret_cast<const char*>(&statistics_18_8.traversal_steps), sizeof(size_t));
        intersections_18_8_file.write(reinterpret_cast<const char*>(&statistics_18_8.intersections), sizeof(size_t));
        traversal_steps_19_5_file.write(reinterpret_cast<const char*>(&statistics_19_5.traversal_steps), sizeof(size_t));
        intersections_19_5_file.write(reinterpret_cast<const char*>(&statistics_19_5.intersections), sizeof(size_t));
        traversal_steps_19_6_file.write(reinterpret_cast<const char*>(&statistics_19_6.traversal_steps), sizeof(size_t));
        intersections_19_6_file.write(reinterpret_cast<const char*>(&statistics_19_6.intersections), sizeof(size_t));
        traversal_steps_19_7_file.write(reinterpret_cast<const char*>(&statistics_19_7.traversal_steps), sizeof(size_t));
        intersections_19_7_file.write(reinterpret_cast<const char*>(&statistics_19_7.intersections), sizeof(size_t));
        traversal_steps_19_8_file.write(reinterpret_cast<const char*>(&statistics_19_8.traversal_steps), sizeof(size_t));
        intersections_19_8_file.write(reinterpret_cast<const char*>(&statistics_19_8.intersections), sizeof(size_t));
        traversal_steps_20_5_file.write(reinterpret_cast<const char*>(&statistics_20_5.traversal_steps), sizeof(size_t));
        intersections_20_5_file.write(reinterpret_cast<const char*>(&statistics_20_5.intersections), sizeof(size_t));
        traversal_steps_20_6_file.write(reinterpret_cast<const char*>(&statistics_20_6.traversal_steps), sizeof(size_t));
        intersections_20_6_file.write(reinterpret_cast<const char*>(&statistics_20_6.intersections), sizeof(size_t));
        traversal_steps_20_7_file.write(reinterpret_cast<const char*>(&statistics_20_7.traversal_steps), sizeof(size_t));
        intersections_20_7_file.write(reinterpret_cast<const char*>(&statistics_20_7.intersections), sizeof(size_t));
        traversal_steps_20_8_file.write(reinterpret_cast<const char*>(&statistics_20_8.traversal_steps), sizeof(size_t));
        intersections_20_8_file.write(reinterpret_cast<const char*>(&statistics_20_8.intersections), sizeof(size_t));
        traversal_steps_21_5_file.write(reinterpret_cast<const char*>(&statistics_21_5.traversal_steps), sizeof(size_t));
        intersections_21_5_file.write(reinterpret_cast<const char*>(&statistics_21_5.intersections), sizeof(size_t));
        traversal_steps_21_6_file.write(reinterpret_cast<const char*>(&statistics_21_6.traversal_steps), sizeof(size_t));
        intersections_21_6_file.write(reinterpret_cast<const char*>(&statistics_21_6.intersections), sizeof(size_t));
        traversal_steps_21_7_file.write(reinterpret_cast<const char*>(&statistics_21_7.traversal_steps), sizeof(size_t));
        intersections_21_7_file.write(reinterpret_cast<const char*>(&statistics_21_7.intersections), sizeof(size_t));
        traversal_steps_21_8_file.write(reinterpret_cast<const char*>(&statistics_21_8.traversal_steps), sizeof(size_t));
        intersections_21_8_file.write(reinterpret_cast<const char*>(&statistics_21_8.intersections), sizeof(size_t));
        traversal_steps_22_5_file.write(reinterpret_cast<const char*>(&statistics_22_5.traversal_steps), sizeof(size_t));
        intersections_22_5_file.write(reinterpret_cast<const char*>(&statistics_22_5.intersections), sizeof(size_t));
        traversal_steps_22_6_file.write(reinterpret_cast<const char*>(&statistics_22_6.traversal_steps), sizeof(size_t));
        intersections_22_6_file.write(reinterpret_cast<const char*>(&statistics_22_6.intersections), sizeof(size_t));
        traversal_steps_22_7_file.write(reinterpret_cast<const char*>(&statistics_22_7.traversal_steps), sizeof(size_t));
        intersections_22_7_file.write(reinterpret_cast<const char*>(&statistics_22_7.intersections), sizeof(size_t));
        traversal_steps_22_8_file.write(reinterpret_cast<const char*>(&statistics_22_8.traversal_steps), sizeof(size_t));
        intersections_22_8_file.write(reinterpret_cast<const char*>(&statistics_22_8.intersections), sizeof(size_t));
        traversal_steps_23_5_file.write(reinterpret_cast<const char*>(&statistics_23_5.traversal_steps), sizeof(size_t));
        intersections_23_5_file.write(reinterpret_cast<const char*>(&statistics_23_5.intersections), sizeof(size_t));
        traversal_steps_23_6_file.write(reinterpret_cast<const char*>(&statistics_23_6.traversal_steps), sizeof(size_t));
        intersections_23_6_file.write(reinterpret_cast<const char*>(&statistics_23_6.intersections), sizeof(size_t));
        traversal_steps_23_7_file.write(reinterpret_cast<const char*>(&statistics_23_7.traversal_steps), sizeof(size_t));
        intersections_23_7_file.write(reinterpret_cast<const char*>(&statistics_23_7.intersections), sizeof(size_t));
        traversal_steps_23_8_file.write(reinterpret_cast<const char*>(&statistics_23_8.traversal_steps), sizeof(size_t));
        intersections_23_8_file.write(reinterpret_cast<const char*>(&statistics_23_8.intersections), sizeof(size_t));

        ref_traversal_steps_file.write(reinterpret_cast<const char*>(&ref_statistics.traversal_steps), sizeof(size_t));
        ref_intersections_file.write(reinterpret_cast<const char*>(&ref_statistics.intersections), sizeof(size_t));

        finished_cnt++;
        std::cout << finished_cnt << std::endl;
    }
}
